version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET=${SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_SECRET=${GOOGLE_SECRET}
      - GOOGLE_CALLBACK=${GOOGLE_CALLBACK}
      - WAYFAIR_TOKEN=${WAYFAIR_TOKEN}
      - WAYFAIR_LOGIN=${WAYFAIR_LOGIN}
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: